# Site settings
title: M SPORT
email: msport@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ျမန္မာနိုင္ငံမွ အားကစားနွင့္ ေဘာလုံးဝါသနာရွင္မ်ားအတြက္ 
  M Sports "Myanmar Sport" မွ ျမန္မာေၾကးျဖင့္ ေဆာ့ကစား 
  နုိင္သည့္ ဆုိဒ္မ်ားအား ဝန္ေဆာင္မႈ ရယူႏုိင္ပါျပီ။ Agents and    
  Members မ်ားအတြက္ ေငြေၾကးယုံၾကည္ စိတ္ခ်ရမႈအျပင္  ေစ်းနႈန္းအားျဖင့္ လူတိုင္းလက္လွမ္းမွီႏိုင္သည့္ အေကာင္းဆုံ ဝန္ေဆာင္မႈ ျဖစ္ပါသည္။
  
baseurl: "https://msports.github.io/" # the subpath of your site, e.g. /blog/
url: "https://msports.github.io/" # the base hostname & protocol for your site
facebook_username: myanmarsport
github_username:  msports

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:http://fb.me/myanmarsport
    name: Facebook
    link: #
  option2:
    name: Viber
    link: #
  option3:
    name: Order
    link: #

# Build settings
markdown: kramdown
