# Site settings
title: M SPORTS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ျမန္မာနိုင္ငံမွ အားကစားနွင့္ ေဘာလုံးဝါသနာရွင္မ်ားအတြက္ 
  M Sports "Myanmar Sports" မွ ျမန္မာေၾကးျဖင့္ ေဆာ့ကစား 
  နုိင္သည့္ ဆုိဒ္မ်ားအား ဝန္ေဆာင္မႈ ရယူႏုိင္ပါျပီ။ Agents and    
  Members မ်ားအတြက္ ေငြေၾကးယုံၾကည္ စိတ္ခ်ရမႈအျပင္  ေစ်းနႈန္းအားျဖင့္ လူတိုင္းလက္လွမ္းမွီႏိုင္သည့္ အေကာင္းဆုံ ဝန္ေဆာင္မႈ ျဖစ္ပါသည္။
  
baseurl: "http://mmsportservice.com" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  egobrightan

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Facebook
    link: www.facebook.com/myanmarsport
  option2:
    name: Viber
    link: #
  option3:
    name: Order
    link: #

# Build settings
markdown: kramdown
